spring:
  jpa:
    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  datasource:
    username: lpfpaaiejyyswv
    password: 086ebcfa175bde0ecc31ae118b1e4df880514e6cc23d1725170a30dfc1066fd0
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-99-80-170-190.eu-west-1.compute.amazonaws.com:5432/de2t6q4afp54an
cors:
  allowed-origins: 'https://ilearning-task-5-client.herokuapp.com/'
  allowed-methods: '*'
  allow-credentials: 'true'
  allowed-headers: '*'
  mapping: '/**'
web-socket:
  app: '/app'
  user: '/user'
  broker: '/chat'
  endpoint: '/ws'
  allowed-origins: '*'
